// Generated by CoffeeScript 1.4.0
(function() {
  var draw;

  draw = function(data) {
    var a, colorScale, colors, darkBlue, e, edges, force, gray, green, h, maxAuthors, minAuthors, nodes, pad, red, svg, tip, w, _i, _j, _len, _len1, _ref, _ref1;
    w = 750;
    h = 750;
    pad = {
      left: 60,
      top: 40,
      right: 40,
      bottom: 40
    };
    darkBlue = "darkslateblue";
    green = "#060";
    gray = "#aaa";
    red = "crimson";
    data.edges2 = [];
    _ref = data.edges;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      e = _ref[_i];
      data.edges2.push({
        source: e[0],
        target: e[1]
      });
    }
    minAuthors = 50;
    maxAuthors = 0;
    _ref1 = data.abstracts;
    for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
      a = _ref1[_j];
      if (a.nauthors < minAuthors) {
        minAuthors = a.nauthors;
      }
      if (a.nauthors > maxAuthors) {
        maxAuthors = a.nauthors;
      }
    }
    tip = d3.svg.tip().orient("right").padding(3).text(function(d) {
      return "" + d.type + " " + d.number;
    }).attr("class", "d3-tip").attr("id", "tip");
    force = d3.layout.force().nodes(data.abstracts).links(data.edges2).size([w, h]).linkDistance([50]).charge([-100]).start();
    colors = d3.scale.category10();
    svg = d3.select("div#abstracts").append("svg").attr("width", w + pad.left + pad.right).attr("height", h + pad.top + pad.bottom);
    svg.append("rect").attr("x", pad.left).attr("y", pad.top).attr("width", w).attr("height", h).attr("fill", "none").attr("stroke", "black").attr("stroke-width", 2);
    colorScale = d3.scale.log().domain([1, maxAuthors]).range(["white", darkBlue]).clamp(true);
    edges = svg.selectAll("line").data(data.edges2).enter().append("line").style("stroke", gray).style("stroke-width", 1);
    nodes = svg.selectAll("circle").data(data.abstracts).enter().append("a").attr("xlink:href", function(d) {
      return "" + d.file;
    }).append("circle").attr("r", 10).style("fill", function(d) {
      return colorScale(d.nauthors);
    }).style("stroke", "black").style("stroke-width", 1).call(force.drag).on("mouseover", function(d) {
      d3.select(this).attr("r", 15);
      d3.select("body").selectAll("p#title").text(d.title);
      return tip.call(this, d);
    }).on("mouseout", function(d) {
      d3.select(this).attr("r", 10);
      d3.select("body").selectAll("p#title").text("");
      return d3.selectAll("#tip").remove();
    }).on("click", function(d) {
      d3.select(this).attr("r", 10);
      d3.select("body").select("p#title").text("");
      return d3.selectAll("#tip").remove();
    });
    return force.on("tick", function() {
      edges.attr("x1", function(d) {
        return d.source.x + pad.left;
      }).attr("y1", function(d) {
        return d.source.y + pad.top;
      }).attr("x2", function(d) {
        return d.target.x + pad.left;
      }).attr("y2", function(d) {
        return d.target.y + pad.top;
      });
      return nodes.attr("cx", function(d) {
        return d.x + pad.left;
      }).attr("cy", function(d) {
        return d.y + pad.top;
      });
    });
  };

  d3.json("abstracts.json", draw);

}).call(this);
