all: programvis/programvis.js vis/force_abstracts.js vis/force_authors.js

programvis/programvis.js: programvis/programvis.coffee
	coffee -c programvis/programvis.coffee

vis/force_abstracts.js: vis/force_abstracts.coffee
	coffee -c vis/force_abstracts.coffee

vis/force_authors.js: vis/force_authors.coffee
	coffee -c vis/force_authors.coffee

